### ISSUE TITLE
Cloud run tasks end up in "failed" state as opposed to completing when timeout is reached

### ISSUE THREAD

**Issue by bjornhanss0n** [dumkydewilde/snowplow-serverless#5]
I've been trying a setup similar to yours, however, the tasks end up as failed instead of completed once the designated timeout is reached. How did you get around that?

**Comment by dumkydewilde** [comment]
@bjornhanss0n you are right, and this has annoyed me as well. The jobs are technically failing as they are just listening to new messages for X amount of time until they are un-gracefully shut down. They are however processing the events. I haven’t figured out how to shut them down gracefully when the queue is empty without getting into more complexity than it is worth though. So for now I guess you’ll have to live with that ‘failed’ status unfortunately.
